services:
  savecloud-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savecloud-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SYNC_GAMES_API_KEY=${SYNC_GAMES_API_KEY:-sg_secret_key_12345}
      - BUCKET_NAME=savecloud-saves
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT:-http://localhost:9000}
      - S3_FORCE_PATH_STYLE=true
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - GAME_STATS_TABLE=savecloud-game-stats
      - SAVE_FILES_INDEX_TABLE=savecloud-save-files-index
      - CONNECTIONS_TABLE=savecloud-connections
      - ENABLE_SEED_WORKER=${ENABLE_SEED_WORKER:-true}
    depends_on:
      - minio
      - dynamodb-local

  minio:
    image: minio/minio:latest
    container_name: savecloud-minio
    restart: unless-stopped
    ports:
      - "9000:9000" # Puerto de API S3
      - "9001:9001" # Panel de administración Web (http://localhost:9001)
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_NOTIFY_WEBHOOK_ENABLE_primary=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary=http://savecloud-api:3000/webhooks/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc
    container_name: savecloud-create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo 'Esperando a MinIO...'; sleep 1; done;
      /usr/bin/mc mb myminio/savecloud-saves --ignore-existing;
      /usr/bin/mc event add myminio/savecloud-saves arn:minio:sqs::primary:webhook --event put,delete --ignore-existing;
      echo 'Bucket S3 savecloud-saves y notificaciones MinIO configurados!';
      exit 0;
      "

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: savecloud-dynamodb
    restart: unless-stopped
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  minio_data:
  dynamodb_data:
